### ISSUE TITLE
Error Report

### ISSUE THREAD

**Issue by chrmina** [tumuyan/MusicBeePlug_AlbumCover#4]
Here is the error I got. The player continues to play until I click OK on the error message.

MusicBee v3.4.8033.18564D  (Win10.0), 19 Dec 2022 14:39:

System.NullReferenceException: Object reference not set to an instance of an object.
   at MusicBeePlugin.Plugin.VGMdbAlbum..ctor(String url)
   at MusicBeePlugin.Plugin.loadVGMdbAlbum(Object url)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by tumuyan** [comment]
does it always shows error and never works?
if not , what content have you search? please upload a screenshot

**Comment by chrmina** [comment]
The error appears randomly. The text I posted is from the window showing the error. A screenshot will just show that!

**Comment by LordFoogThe4rd** [comment]
same error. this appears randomly when searching for album art online or tuning in a radio station for me

**Comment by TheDwellerInDarkness** [comment]
I have the same error too, even after upgrading to the latest version.

**Comment by tumuyan** [comment]
The vgmdb.info API not works well.
I have update the plug and it could search from vgmdb.net. Also you could run a vgmdb API server and config the API server.
